name: clinic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  web: ^1.1.1
  flutter_native_splash: ^2.4.8
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/argana_bg.png
    - assets/argana_title.png
    - assets/argana_c_logo.png
    - assets/pdf_logo_argana.png
