# Generated by Django 6.0.1 on 2026-02-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='core.medecin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('CONFIRME', 'Confirme'), ('ANNULE', 'Annule'), ('TERMINE', 'Termine'), ('ATTENTE', 'En attente')], default='ATTENTE', max_length=10),
        ),
    ]
