# Generated by Django 6.0.3 on 2026-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ARRIVE', 'Arrivé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='ATTENTE', max_length=10),
        ),
    ]
